assigneemap: {"zeus":"4373", "room":"2", "liveservice":"3"}
#  https://gitlab.gz.cvte.cn/api/v4/users?username=i_linjunyi
#  https:// gitlab地址 /api/v4/users?username= 用户名

serviceinfo:
  checkTime: 60
  agreement: http
  address: 10.10.14.60
  port: 8500
  prefix: /v1/health/service/mindlinker-
  suffix: -dev?passing

gitlab:
  tokenKey: PRIVATE-TOKEN
  tokenValue: glpat-nyzxmto439EJP7tojKDT
  agreement: https
  address: gitlab.gz.cvte.cn
  targetBranch: feature/addComitInfo

createmr:
  title: "上线自动合并master"